// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_Buoi5.Models;

#nullable disable

namespace Web_Buoi5.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250618132445_RemoveBooksFromCategory")]
    partial class RemoveBooksFromCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web_Buoi5.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Nguyễn Nhật Ánh",
                            CategoryId = 1,
                            Description = "Tập hợp những câu chuyện ngắn đầy cảm xúc về tuổi thơ.",
                            ImagePath = "/ImageBooks/b1.jpg",
                            Price = 120000m,
                            Title = "Sách Trốn Lên Mái Nhà Khóc"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Nguyễn Nhật Ánh",
                            CategoryId = 1,
                            Description = "Hồi ức tuổi thơ đầy cảm xúc tại làng quê Việt Nam.",
                            ImagePath = "/ImageBooks/b2.jpg",
                            Price = 150000m,
                            Title = "Tôi Thấy Hoa Vàng Trên Cỏ Xanh"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Dale Carnegie",
                            CategoryId = 2,
                            Description = "Cuốn sách kinh điển về nghệ thuật giao tiếp và thuyết phục.",
                            ImagePath = "/ImageBooks/b3.jpg",
                            Price = 180000m,
                            Title = "Đắc Nhân Tâm"
                        });
                });

            modelBuilder.Entity("Web_Buoi5.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Văn học"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tâm lý"
                        });
                });

            modelBuilder.Entity("Web_Buoi5.Models.Book", b =>
                {
                    b.HasOne("Web_Buoi5.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
